config/routes.rb
ClassProject::Application.routes.draw do
  resources :searches do
    collection do
      get 'time_search'
      get 'avgSearch'
    end
  end

  resources :reports

  resources :transactions

  resources :items
  get "searches/time_search"
  get '_periodReport' => 'search#periodReport'
  get '_items' => 'item#items'

end

app/controllers/time_searches_controller.rb
class TimeSearchesController < ApplicationController
  before_action :set_time_search, only: [:show, :edit, :update, :destroy]

  # GET /time_searches
  # GET /time_searches.json
  def index
    @time_searches = Search.all
  end

  # GET /time_searches/1
  # GET /time_searches/1.json
  def show
  end

  # GET /time_searches/new
  def new
    @time_search = Search.new
  end

  # GET /time_searches/1/edit
  def edit
  end

  # POST /time_searches
  # POST /time_searches.json
  def create
    @time_search = Search.new(time_search_params)

    respond_to do |format|
      if @time_search.save
        format.html { redirect_to @time_search, notice: 'Time search was successfully created.' }
        format.json { render action: 'show', status: :created, location: @time_search }
      else
        format.html { render action: 'new' }
        format.json { render json: @time_search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_searches/1
  # PATCH/PUT /time_searches/1.json
  def update
    respond_to do |format|
      if @time_search.update(time_search_params)
        format.html { redirect_to @time_search, notice: 'Time search was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @time_search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_searches/1
  # DELETE /time_searches/1.json
  def destroy
    @time_search.destroy
    respond_to do |format|
      format.html { redirect_to time_searches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_search
      @time_search = Search.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_search_params
      params[:time_search]
    end
end

app/helpers/time_searches_helper.rb
module TimeSearchesHelper
end

app/views/time_searches/_form.html.erb
<%= form_for(@time_search) do |f| %>
  <% if @time_search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_search.errors.count, "error") %> prohibited this time_search from being saved:</h2>

      <ul>
      <% @time_search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/time_searches/edit.html.erb
<h1>Editing time_search</h1>

<%= render 'form' %>

<%= link_to 'Show', @time_search %> |
<%= link_to 'Back', time_searches_path %>

app/views/time_searches/index.html.erb
<h1>Listing time_searches</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @time_searches.each do |time_search| %>
      <tr>
        <td><%= link_to 'Show', time_search %></td>
        <td><%= link_to 'Edit', edit_time_search_path(time_search) %></td>
        <td><%= link_to 'Destroy', time_search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time search', new_time_search_path %>

app/views/time_searches/new.html.erb
<h1>New time_search</h1>

<%= render 'form' %>

<%= link_to 'Back', time_searches_path %>

app/views/time_searches/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_time_search_path(@time_search) %> |
<%= link_to 'Back', time_searches_path %>