config/routes.rb
ClassProject::Application.routes.draw do
  resources :searches do
    collection do
      get 'time_search'
      get 'avgSearch'
    end
  end

  resources :reports

  resources :transactions

  resources :items
  get "searches/time_search"
  get '_periodReport' => 'search#periodReport'
  get '_items' => 'item#items'

end

app/models/search.rb
class Search < ActiveRecord::Base
  belongs_to :transaction
  belongs_to :item
  def find_items
    products = Item.order(:name)
    products = Items.where("quantity <= ?",quantity)
  end

  def find_transactions
    transactions = Transaction.order(:sale_date)
    transactions = transactions.where("date >= ?", start_date)
    transactions = transactions.where("date <= ?", end_date)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render action: 'show', status: :created, location: @search }
      else
        format.html { render action: 'new' }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url }
      format.json { head :no_content }
    end

    def time_search
     @searches = Search.new
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:search).permit(:transaction_id, :item_id, :item_name, :quantity, :start_date, :end_date)
    end


end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_avgSearch.html.erb
<h1>Average Search</h1>

<% @search.transactions.each do |b| %>
    <p><%="Item ID: #{b.item_id}"%>
      <%="Average: #{b.quantity}"%></p>
<%end%>

<%= link_to 'Back', searches_path %>

app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :transaction_id %><br>
    <%= f.number_field :transaction_id %>
  </div>
  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.number_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :item_name %><br>
    <%= f.text_field :item_name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/searches/_periodReport.html.erb


<h1>Period Search</h1>

<%= form_for (@search) do |f|%>

    <div class="field">
      <%=f.label :start_date%><br />
      <%=f.date_select :start_date, :order => [:month, :day, :year]%>
    </div>

    <div class = "field">
      <%f.label :end_date%><br />
      <%=f.date_select :end_date, :order => [:month, :day, :year]%>
    </div>

    <div class="actions">
      <%=f.submit "Search"%>
    </div>
<%end%>

<%= link_to 'Back', searches_path %>

app/views/searches/avgSearch.html.erb
<h1>Product Avg Search</h1>

<p>Please enter a Product ID to show the average number of that item sold per week</p>

<%= form_for (@search) do |f|%>

    <div class="field">
      <%=f.label :item_id%><br />
      <%=f.text_field :item_id%>
    </div>

    <div class="actions">
      <%=f.submit "Search"%>
    </div>
<%end%>

app/views/searches/edit.html.erb
<h1>Editing search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<h1>Please choose a search</h1>

<br>
<p></p><%= link_to "Quantity Search", new_search_path%></p>
<%= link_to "Date Search", searches_time_search_path%>

app/views/searches/new.html.erb
<h1>Quantity Search</h1>

<p>Select a number to show all products with <= to that number</p>

<%= form_for (@search) do |f|%>

    <div class="field">
      <%=f.label :quantity%><br />
      <%=f.text_field :quantity%>
    </div>

    <div class="actions">
      <%=f.submit "Search"%>
    </div>
<%end%>


<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<%if @search.quantity!=nil%>
    <%= render :partial => 'items/items'%>

    <%if @search.item_id!=nil%>
        <%= render :partial => "searches/avgSearch"%>

    <%else%>
        <%= render :partial => "transactions/periodReport"%>
    <%end%>
<%end%>

<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>

app/views/searches/time_search.html.erb
<h1>Date Search</h1>

<p>Select a time frame for which to search for sales</p>


<%= form_for (@search) do |f|%>

    <div class="field">
      <%=f.label :start_date%><br />
      <%=f.date_select :start_date, :order => [:month, :day, :year]%>
    </div>

    <div class = "field">
      <%=f.label :end_date%><br />
      <%=f.date_select :end_date, :order => [:month, :day, :year]%>
    </div>

    <div class="actions">
      <%=f.submit "Search"%>
    </div>
<%end%>


<%= link_to 'Back', searches_path %>